version: "2"

run:
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly
  build-tags:
    - integration

linters:
  disable:
    - gocyclo
    - wsl

  settings:
    govet:
      enable:
        - shadow

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
      - path: gen/.*\.pb\.go   # Исключаем сгенерированные файлы
        linters:
          - revive
          - govet
          - staticcheck
      - path: examples/.*       # Исключаем примеры
        linters:
          - revive

issues:
  max-issues-per-linter: 100
  max-same-issues: 100