version: 2

project_name: voyager

builds:
  - id: voyagerd
    binary: voyagerd
    main: ./cmd/voyagerd
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env: [CGO_ENABLED=0]

archives:
  - format: tar.gz
    name_template: "voyager_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - deployments/kubernetes/*.yaml
      - deployments/systemd/*.service

checksum:
  name_template: "voyager_{{ .Version }}_checksums.txt"

release:
  github:
    owner: kolkov
    name: voyager
  draft: true
  prerelease: auto