project_name: voyager

builds:
  - id: voyagerd
    binary: voyagerd
    main: ./cmd/voyagerd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

  - id: order-service
    binary: order-service
    main: ./examples/order-service
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: payment-service
    binary: payment-service
    main: ./examples/payment-service
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: discovery-server
    binary: discovery-server
    main: ./examples/discovery-server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - deployments/kubernetes/*
      - deployments/systemd/*

dockers:
  - image_templates:
      - "ghcr.io/kolkov/voyagerd:{{ .Version }}"
      - "ghcr.io/kolkov/voyagerd:latest"
    dockerfile: cmd/voyagerd/Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.Commit}}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: kolkov
    name: voyager
  draft: true
  prerelease: auto