version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd -advertise-client-urls http://etcd:2379 -listen-client-urls http://0.0.0.0:2379
    networks:
      - voyager-net

  voyager-discovery:
    image: voyagerd:${VERSION:-latest}
    environment:
      VOYAGER_ETCD_ENDPOINTS: "etcd:2379"
      VOYAGER_AUTH_TOKEN: "secure-token"
    ports:
      - "50050:50050"
    depends_on:
      - etcd
    networks:
      - voyager-net

  order-service:
    image: voyager-example-order-service:${DOCKER_TAG:-latest}
    environment:
      VOYAGER_ADDR: "voyager-discovery:50050"
    ports:
      - "8080:8080"
    depends_on:
      - voyager-discovery
    networks:
      - voyager-net

  payment-service:
    image: voyager-example-payment-service:${DOCKER_TAG:-latest}
    environment:
      VOYAGER_ADDR: "voyager-discovery:50050"
    ports:
      - "8081:8081"
    depends_on:
      - voyager-discovery
    networks:
      - voyager-net

networks:
  voyager-net:
    driver: bridge